version: '3.8'
services:
  db:
    image: postgres:15.1-alpine3.17
    container_name: PostgresShoppingDB
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '3433:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
