version: '3.8'
services:
  db:
    image: postgres:15.1-alpine3.17
    container_name: PostgresShoppingDB
    restart: always
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - '7524:7524'
    volumes:
      - ./postgres:/var/lib/postgresql/data
